package repodb.db;

import java.sql.Connection;
import java.sql.SQLException;

import repodb.db.mappers.ResultSetMapper;
import repodb.db.uow.UnitOfWork;
import repodb.domian.Contact;

public class ContactRepository extends RepositoryBase<Contact> {

	Connection connection;

	protected String tableName(){
		return "contact";
	}
	protected String createTableSql(){
		return "CREATE TABLE contact(id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(30),"
				+ "surname VARCHAR(50), phone VARCHAR(11), age INT, email VARCHAR(30), localization VARCHAR(20))";
	}  
	protected String deleteSql(){
		return "DELETE FROM contact WHERE id=?";
	}
	protected String insertSql(){
		return "INSERT INTO contact(name, surname, phone, age, email, localization) VALUES(?,?,?,?,?,?)";
	}
	protected String selectAllSql(){
		return "SELECT * FROM contact";
	}
	protected String selectByIdSql(){
		return "SELECT * FROM contact WHERE id=?";
	}
	protected String updateSql(){
		return "UPDATE contact SET name=?, surname=?, phone=?, age=?, email=?, localization=? WHERE id=?";
	}
	
	public ContactRepository(Connection connection, ResultSetMapper<Contact> mapper, UnitOfWork uow) throws SQLException{		
		super(connection, mapper, uow);
	}
	
	protected void setupUpdate(Contact contact) throws SQLException {
		update.setString(1, contact.getName());
		update.setString(2, contact.getSurname());
		update.setString(3, contact.getPhone());
		update.setInt(4, contact.getAge());
		update.setString(5, contact.getEmail());
		update.setString(6, contact.getLocalization());
		update.setInt(7, contact.getId());
	}
	
	protected void setupInsert(Contact contact) throws SQLException {
		insert.setString(1, contact.getName());
		insert.setString(2, contact.getSurname());
		insert.setString(3, contact.getPhone());
		insert.setInt(4, contact.getAge());
		insert.setString(5, contact.getEmail());
		insert.setString(6, contact.getLocalization());
	}
	public Connection getConnection() {
		return connection;
	}
	
	public void setConnection(Connection connection) {
		this.connection = connection;
	}

	
}